version: '2'
services:
  gdb3-app:
    image: gdb3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://gdb3-mariadb:3306/gdb3
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://gdb3-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gdb3-elasticsearch:9200
    ports:
      - 8080:8080
  gdb3-mariadb:
    extends:
      file: mariadb.yml
      service: gdb3-mariadb
  gdb3-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gdb3-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
